console.log("Start Initializing RWGPS");

function addScript(url, id) {
    console.log("Adding script: " + url);

    const script = document.createElement('script');
    script.src = url;
    script.id = id;

    document.head.appendChild(script);
}

function Init() {
    console.log("Initializing RWGPS");

    var instance = window.rwgps.MapDelegate.getMapInstance();
    if (instance == null) {
        return '0';
    }

    console.log("RWGPS Map Instance found");

    window.mapInstance = instance;

    console.log("RWGPS Map Instance lyer: " + window.mapInstance.getLayersOrder().length);

    instance.on('idle', () => {
        console.log("RWGPS Map idle");
        
        LayerControl();
    });

    instance.on('render', LayerControl);

    setInterval(LayerControl, 200);

    return '1';
}

function AddLayers(){
    console.log("Adding layers to RWGPS Map");

    if (window.rwgps.MapDelegate.props.mapInstance.__gm) {
        console.log("RWGPS Map Instance is Google Maps, not supported yet");

        return;
    }
    
    window.mapInstance.addSource('ltc2tiles', {
        'type': 'vector',
        'tiles': [' http://localhost:50000/api/Tiles/tile/{z}/{x}/{y}.pbf'],
        'minzoom': 3,
        'maxzoom': 17
    });


    window.mapInstance.addLayer({
        'id': 'fltc2tiles',
        'type': 'fill',
        'source': 'ltc2tiles',
        'source-layer': 'geojsonLayer',
        'paint': {
            'fill-opacity': 0.3,
            'fill-color': 'rgb(0,0,0)'
        }
    });

    window.mapInstance.addLayer({
        'id': 'ltc2tiles',
        'type': 'line',
        'source': 'ltc2tiles',
        'source-layer': 'geojsonLayer',
        'layout': {
            'line-cap': 'round',
            'line-join': 'round'
        },
        'paint': {
            'line-opacity': 1.0,
            'line-color': 'rgb(0,0,0)',
            'line-width': 2
        }
    });
}

function LayerControl() 
{
    var instance = window.rwgps.MapDelegate.getMapInstance();

    if (instance != window.mapInstance) {
        
        console.log("RWGPS Map Instance changed");
        
        window.mapInstance = instance;

        if (window.rwgps.MapDelegate.props.mapInstance.__gm) 
        {
            console.log("RWGPS Map Instance is now Google Maps");

            if (document.getElementById("ltc2-deckgl")) {
                console.log("Deck.gl script already added");
            } else {
                //addScript("https://unpkg.com/deck.gl@9.2.11/dist.min.js", "ltc2-deckgl");
            }
        } else {
            console.log("RWGPS Map Instance layers changed, adding layers");
            
            AddLayers();

            instance.on('idle', () => {
                console.log("RWGPS Map idle");
        
                LayerControl();
            });

            instance.on('render', LayerControl);
        }
    } else {
        if (!window.rwgps.MapDelegate.props.mapInstance.__gm) {
            var layers = window.mapInstance.getLayersOrder();

            if (layers.length >= 1 && layers[layers.length-1] != "ltc2tiles") {
                console.log("RWGPS Map Instance layers changed, re-adding layers");
                
                AddLayers();

                instance.on('idle', () => {
                    console.log("RWGPS Map idle");
        
                    LayerControl();
                });

                instance.on('render', LayerControl);
            }
        }
    }
}


Init();